name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
name: the name of this workflow.
on.push.branches: specifies that this workflow should run on every push event for the branches in the list.
jobs: creates a job ID (build) and declares the type of machine that the job should run on.
For more information about the YAML syntax used here, see Workflow syntax for GitHub Actions.

Step three: Define the workflow steps
Now the essentials: what steps to run, and in what order to run them.


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
The previous YAML snippet contains a sequence of steps that:

Checks out the repository on the build machine.
Signs in to Docker Hub, using the Docker Login action and your Docker Hub credentials.
Creates a BuildKit builder instance using the Docker Setup Buildx action.
Builds the container image and pushes it to the Docker Hub repository, using Build and push Docker images.

The with key lists a number of input parameters that configures the step:

context: the build context.
file: filepath to the Dockerfile.
push: tells the action to upload the image to a registry after building it.
tags: tags that specify where to push the image.
Add these steps to your workflow file. The full workflow configuration should look as follows:


name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/clockbox:latest
